language: node_js
node_js: stable
# S: Build Lifecycle
install:
  - npm install
cache:
  directories:
  - node_modules
before_install:
  - npm install -g hexo-cli
script:
  - hexo g
after_script:
  - git clone https://${GH_REF} .deploy_git
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./public/ 
  - cd ./public
  - git config user.name "sh"
  - git config user.email "2662419405@qq.com"
  - git add .
  - git commit -m "TravisCI 自动部署"
  # Github Pages
  - git push --force --quiet "https://${githubblog}@${GH_REF}" master:master
env:
  global:
    - GH_REF: github.com/2662419405/2662419405.github.io.git
notifications:
  email:
    - 2662419405@qq.com
    - qq2662419405@163.com
  on_success: change
  on_failure: always
